language: php

sudo: true

php:
  - hhvm
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm

before_install:
  - composer self-update
  - sh -e build/travis/scripts/apt-get.sh
  - sh -e build/travis/scripts/apache2-vhost.sh
  - sh -e build/travis/scripts/apache2-configure.sh

before_script:
  - composer update --dev
  - phpenv rehash

script:
  - phpunit --configuration phpunit.travis.xml
